rare_first_num=[ 8,  22,  27,  44,  50,  55,  62,  63,  66,  70,  76,  77,  80,  83,
         84,  90,  99, 100, 104, 107, 112, 127, 135, 136, 149, 158, 165, 166,
        168, 172, 179, 181, 184, 188, 189, 192, 195, 198, 205, 206, 214, 216,
        222, 227, 229, 238, 239, 254, 255, 257, 260, 261, 262, 274, 279, 280,
        281, 286, 289, 292, 303, 311, 315, 317, 325, 328, 333, 334, 345, 350,
        351, 354, 358, 364, 379, 381, 389, 390, 391, 395, 397, 398, 399, 401,
        402, 403, 404, 405, 407, 410, 416, 418, 426, 427, 429, 431, 436, 439,
        440, 449, 451, 463, 469, 474, 482, 485, 498, 499, 504, 509, 514, 517,
        520, 522, 526, 531, 535, 539, 546, 547, 548, 549, 550, 551, 552, 555,
        556, 560, 578, 580, 581, 586, 592, 593, 595, 596, 597, 599]
nonrare_first_num=[0,   1,   2,   3,   4,   5,   6,   7,   9,  10,  11,  12,  13,  14,
         15,  16,  17,  18,  19,  20,  21,  23,  24,  25,  26,  28,  29,  30,
         31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  45,
         46,  47,  48,  49,  51,  52,  53,  54,  56,  57,  58,  59,  60,  61,
         64,  65,  67,  68,  69,  71,  72,  73,  74,  75,  78,  79,  81,  82,
         85,  86,  87,  88,  89,  91,  92,  93,  94,  95,  96,  97,  98, 101,
        102, 103, 105, 106, 108, 109, 110, 111, 113, 114, 115, 116, 117, 118,
        119, 120, 121, 122, 123, 124, 125, 126, 128, 129, 130, 131, 132, 133,
        134, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 150,
        151, 152, 153, 154, 155, 156, 157, 159, 160, 161, 162, 163, 164, 167,
        169, 170, 171, 173, 174, 175, 176, 177, 178, 180, 182, 183, 185, 186,
        187, 190, 191, 193, 194, 196, 197, 199, 200, 201, 202, 203, 204, 207,
        208, 209, 210, 211, 212, 213, 215, 217, 218, 219, 220, 221, 223, 224,
        225, 226, 228, 230, 231, 232, 233, 234, 235, 236, 237, 240, 241, 242,
        243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 256, 258, 259,
        263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 275, 276, 277,
        278, 282, 283, 284, 285, 287, 288, 290, 291, 293, 294, 295, 296, 297,
        298, 299, 300, 301, 302, 304, 305, 306, 307, 308, 309, 310, 312, 313,
        314, 316, 318, 319, 320, 321, 322, 323, 324, 326, 327, 329, 330, 331,
        332, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 346, 347, 348,
        349, 352, 353, 355, 356, 357, 359, 360, 361, 362, 363, 365, 366, 367,
        368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 380, 382, 383,
        384, 385, 386, 387, 388, 392, 393, 394, 396, 400, 406, 408, 409, 411,
        412, 413, 414, 415, 417, 419, 420, 421, 422, 423, 424, 425, 428, 430,
        432, 433, 434, 435, 437, 438, 441, 442, 443, 444, 445, 446, 447, 448,
        450, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 464, 465,
        466, 467, 468, 470, 471, 472, 473, 475, 476, 477, 478, 479, 480, 481,
        483, 484, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497,
        500, 501, 502, 503, 505, 506, 507, 508, 510, 511, 512, 513, 515, 516,
        518, 519, 521, 523, 524, 525, 527, 528, 529, 530, 532, 533, 534, 536,
        537, 538, 540, 541, 542, 543, 544, 545, 553, 554, 557, 558, 559, 561,
        562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575,
        576, 577, 579, 582, 583, 584, 585, 587, 588, 589, 590, 591, 594, 598]
all_classnames=['board airplane', 'direct airplane', 'exit airplane', 'fly airplane', 'inspect airplane', 'load airplane',
                'ride airplane', 'sit_on airplane', 'wash airplane', 'no_interaction airplane', 'carry bicycle', 'hold bicycle',
                'inspect bicycle', 'jump bicycle', 'hop_on bicycle', 'park bicycle', 'push bicycle', 'repair bicycle', 'ride bicycle',
                'sit_on bicycle', 'straddle bicycle', 'walk bicycle', 'wash bicycle', 'no_interaction bicycle', 'chase bird',
                'feed bird', 'hold bird', 'pet bird', 'release bird', 'watch bird', 'no_interaction bird', 'board boat',
                'drive boat', 'exit boat', 'inspect boat', 'jump boat', 'launch boat', 'repair boat', 'ride boat', 'row boat',
                'sail boat', 'sit_on boat', 'stand_on boat', 'tie boat', 'wash boat', 'no_interaction boat', 'carry bottle',
                'drink_with bottle', 'hold bottle', 'inspect bottle', 'lick bottle', 'open bottle', 'pour bottle', 'no_interaction bottle',
                'board bus', 'direct bus', 'drive bus', 'exit bus', 'inspect bus', 'load bus', 'ride bus', 'sit_on bus', 'wash bus',
                'wave bus', 'no_interaction bus', 'board car', 'direct car', 'drive car', 'hose car', 'inspect car',
                'jump car', 'load car', 'park car', 'ride car', 'wash car', 'no_interaction car', 'dry cat',
                'feed cat', 'hold cat', 'hug cat', 'kiss cat', 'pet cat', 'scratch cat', 'wash cat', 'chase cat',
                'no_interaction cat', 'carry chair', 'hold chair', 'lie_on chair', 'sit_on chair', 'stand_on chair', 'no_interaction chair',
                'carry couch', 'lie_on couch', 'sit_on couch', 'no_interaction couch', 'feed cow', 'herd cow', 'hold cow', 'hug cow', 'kiss cow',
                'lasso cow', 'milk cow', 'pet cow', 'ride cow', 'walk cow', 'no_interaction cow', 'clean dining_table', 'eat_at dining_table',
                'sit_at dining_table', 'no_interaction dining_table', 'carry dog', 'dry dog', 'feed dog', 'groom dog', 'hold dog', 'hose dog',
                'hug dog', 'inspect dog', 'kiss dog', 'pet dog', 'run dog', 'scratch dog', 'straddle dog', 'train dog', 'walk dog', 'wash dog',
                'chase dog', 'no_interaction dog', 'feed horse', 'groom horse', 'hold horse', 'hug horse', 'jump horse', 'kiss horse',
                'load horse', 'hop_on horse', 'pet horse', 'race horse', 'ride horse', 'run horse', 'straddle horse', 'train horse', 'walk horse',
                'wash horse', 'no_interaction horse', 'hold motorcycle', 'inspect motorcycle', 'jump motorcycle', 'hop_on motorcycle',
                'park motorcycle', 'push motorcycle', 'race motorcycle', 'ride motorcycle', 'sit_on motorcycle', 'straddle motorcycle',
                'turn motorcycle', 'walk motorcycle', 'wash motorcycle', 'no_interaction motorcycle', 'carry person', 'greet person',
                'hold person', 'hug person', 'kiss person', 'stab person', 'tag person', 'teach person', 'lick person', 'no_interaction person',
                'carry potted_plant', 'hold potted_plant', 'hose potted_plant', 'no_interaction potted_plant', 'carry sheep', 'feed sheep',
                'herd sheep', 'hold sheep', 'hug sheep', 'kiss sheep', 'pet sheep', 'ride sheep', 'shear sheep', 'walk sheep', 'wash sheep',
                'no_interaction sheep', 'board train', 'drive train', 'exit train', 'load train', 'ride train', 'sit_on train', 'wash train',
                'no_interaction train', 'control tv', 'repair tv', 'watch tv', 'no_interaction tv', 'buy apple', 'cut apple', 'eat apple',
                'hold apple', 'inspect apple', 'peel apple', 'pick apple', 'smell apple', 'wash apple', 'no_interaction apple', 'carry backpack',
                'hold backpack', 'inspect backpack', 'open backpack', 'wear backpack', 'no_interaction backpack', 'buy banana', 'carry banana',
                'cut banana', 'eat banana', 'hold banana', 'inspect banana', 'peel banana', 'pick banana', 'smell banana', 'no_interaction banana',
                'break baseball_bat', 'carry baseball_bat', 'hold baseball_bat', 'sign baseball_bat', 'swing baseball_bat',
                'throw baseball_bat', 'wield baseball_bat', 'no_interaction baseball_bat', 'hold baseball_glove', 'wear baseball_glove',
                'no_interaction baseball_glove', 'feed bear', 'hunt bear', 'watch bear', 'no_interaction bear', 'clean bed', 'lie_on bed',
                'sit_on bed', 'no_interaction bed', 'inspect bench', 'lie_on bench', 'sit_on bench', 'no_interaction bench', 'carry book',
                'hold book', 'open book', 'read book', 'no_interaction book', 'hold bowl', 'stir bowl', 'wash bowl', 'lick bowl', 'no_interaction bowl',
                'cut broccoli', 'eat broccoli', 'hold broccoli', 'smell broccoli', 'stir broccoli', 'wash broccoli', 'no_interaction broccoli',
                'blow cake', 'carry cake', 'cut cake', 'eat cake', 'hold cake', 'light cake', 'make cake', 'pick_up cake', 'no_interaction cake',
                'carry carrot', 'cook carrot', 'cut carrot', 'eat carrot', 'hold carrot', 'peel carrot', 'smell carrot', 'stir carrot',
                'wash carrot', 'no_interaction carrot', 'carry cell_phone', 'hold cell_phone', 'read cell_phone', 'repair cell_phone',
                'talk_on cell_phone', 'text_on cell_phone', 'no_interaction cell_phone', 'check clock', 'hold clock', 'repair clock', 'set clock',
                'no_interaction clock', 'carry cup', 'drink_with cup', 'hold cup', 'inspect cup', 'pour cup', 'sip cup', 'smell cup', 'fill cup',
                'wash cup', 'no_interaction cup', 'buy donut', 'carry donut', 'eat donut', 'hold donut', 'make donut', 'pick_up donut',
                'smell donut', 'no_interaction donut', 'feed elephant', 'hold elephant', 'hose elephant', 'hug elephant', 'kiss elephant',
                'hop_on elephant', 'pet elephant', 'ride elephant', 'walk elephant', 'wash elephant', 'watch elephant', 'no_interaction elephant',
                'hug fire_hydrant', 'inspect fire_hydrant', 'open fire_hydrant', 'paint fire_hydrant', 'no_interaction fire_hydrant', 'hold fork',
                'lift fork', 'stick fork', 'lick fork', 'wash fork', 'no_interaction fork', 'block frisbee', 'catch frisbee', 'hold frisbee',
                'spin frisbee', 'throw frisbee', 'no_interaction frisbee', 'feed giraffe', 'kiss giraffe', 'pet giraffe', 'ride giraffe', 'watch giraffe',
                'no_interaction giraffe', 'hold hair_drier', 'operate hair_drier', 'repair hair_drier', 'no_interaction hair_drier', 'carry handbag',
                'hold handbag', 'inspect handbag', 'no_interaction handbag', 'carry hot_dog', 'cook hot_dog', 'cut hot_dog', 'eat hot_dog',
                'hold hot_dog', 'make hot_dog', 'no_interaction hot_dog', 'carry keyboard', 'clean keyboard', 'hold keyboard', 'type_on keyboard',
                'no_interaction keyboard', 'assemble kite', 'carry kite', 'fly kite', 'hold kite', 'inspect kite', 'launch kite', 'pull kite',
                'no_interaction kite', 'cut_with knife', 'hold knife', 'stick knife', 'wash knife', 'wield knife', 'lick knife', 'no_interaction knife',
                'hold laptop', 'open laptop', 'read laptop', 'repair laptop', 'type_on laptop', 'no_interaction laptop', 'clean microwave',
                'open microwave', 'operate microwave', 'no_interaction microwave', 'control mouse', 'hold mouse', 'repair mouse', 'no_interaction mouse',
                'buy orange', 'cut orange', 'eat orange', 'hold orange', 'inspect orange', 'peel orange', 'pick orange', 'squeeze orange',
                'wash orange', 'no_interaction orange', 'clean oven', 'hold oven', 'inspect oven', 'open oven', 'repair oven', 'operate oven',
                'no_interaction oven', 'check parking_meter', 'pay parking_meter', 'repair parking_meter', 'no_interaction parking_meter',
                'buy pizza', 'carry pizza', 'cook pizza', 'cut pizza', 'eat pizza', 'hold pizza', 'make pizza', 'pick_up pizza', 'slide pizza',
                'smell pizza', 'no_interaction pizza', 'clean refrigerator', 'hold refrigerator', 'move refrigerator', 'open refrigerator',
                'no_interaction refrigerator', 'hold remote', 'point remote', 'swing remote', 'no_interaction remote', 'carry sandwich',
                'cook sandwich', 'cut sandwich', 'eat sandwich', 'hold sandwich', 'make sandwich', 'no_interaction sandwich', 'cut_with scissors',
                'hold scissors', 'open scissors', 'no_interaction scissors', 'clean sink', 'repair sink', 'wash sink', 'no_interaction sink',
                'carry skateboard', 'flip skateboard', 'grind skateboard', 'hold skateboard', 'jump skateboard', 'pick_up skateboard', 'ride skateboard',
                'sit_on skateboard', 'stand_on skateboard', 'no_interaction skateboard', 'adjust skis', 'carry skis', 'hold skis', 'inspect skis',
                'jump skis', 'pick_up skis', 'repair skis', 'ride skis', 'stand_on skis', 'wear skis', 'no_interaction skis', 'adjust snowboard',
                'carry snowboard', 'grind snowboard', 'hold snowboard', 'jump snowboard', 'ride snowboard', 'stand_on snowboard', 'wear snowboard',
                'no_interaction snowboard', 'hold spoon', 'lick spoon', 'wash spoon', 'sip spoon', 'no_interaction spoon', 'block sports_ball',
                'carry sports_ball', 'catch sports_ball', 'dribble sports_ball', 'hit sports_ball', 'hold sports_ball', 'inspect sports_ball',
                'kick sports_ball', 'pick_up sports_ball', 'serve sports_ball', 'sign sports_ball', 'spin sports_ball', 'throw sports_ball',
                'no_interaction sports_ball', 'hold stop_sign', 'stand_under stop_sign', 'stop_at stop_sign', 'no_interaction stop_sign', 'carry suitcase',
                'drag suitcase', 'hold suitcase', 'hug suitcase', 'load suitcase', 'open suitcase', 'pack suitcase', 'pick_up suitcase', 'zip suitcase',
                'no_interaction suitcase', 'carry surfboard', 'drag surfboard', 'hold surfboard', 'inspect surfboard', 'jump surfboard',
                'lie_on surfboard', 'load surfboard', 'ride surfboard', 'stand_on surfboard', 'sit_on surfboard', 'wash surfboard', 'no_interaction surfboard',
                'carry teddy_bear', 'hold teddy_bear', 'hug teddy_bear', 'kiss teddy_bear', 'no_interaction teddy_bear', 'carry tennis_racket',
                'hold tennis_racket', 'inspect tennis_racket', 'swing tennis_racket', 'no_interaction tennis_racket', 'adjust tie', 'cut tie', 'hold tie',
                'inspect tie', 'pull tie', 'tie tie', 'wear tie', 'no_interaction tie', 'hold toaster', 'operate toaster', 'repair toaster',
                'no_interaction toaster', 'clean toilet', 'flush toilet', 'open toilet', 'repair toilet', 'sit_on toilet', 'stand_on toilet',
                'wash toilet', 'no_interaction toilet', 'brush_with toothbrush', 'hold toothbrush', 'wash toothbrush', 'no_interaction toothbrush',
                'install traffic_light', 'repair traffic_light', 'stand_under traffic_light', 'stop_at traffic_light', 'no_interaction traffic_light',
                'direct truck', 'drive truck', 'inspect truck', 'load truck', 'repair truck', 'ride truck', 'sit_on truck', 'wash truck',
                'no_interaction truck', 'carry umbrella', 'hold umbrella', 'lose umbrella', 'open umbrella', 'repair umbrella', 'set umbrella',
                'stand_under umbrella', 'no_interaction umbrella', 'hold vase', 'make vase', 'paint vase', 'no_interaction vase', 'fill wine_glass',
                'hold wine_glass', 'sip wine_glass', 'toast wine_glass', 'lick wine_glass', 'wash wine_glass', 'no_interaction wine_glass', 'feed zebra',
                'hold zebra', 'pet zebra', 'watch zebra', 'no_interaction zebra']
object_seen_name=['sports_ball', 'knife', 'bird', 'giraffe', 'tie', 'snowboard', 'cup', 'backpack', 'kite', 
                  'baseball_glove', 'bus', 'chair', 'oven', 'boat', 'train', 'bicycle', 'teddy_bear', 'bottle', 
                  'dining_table', 'cell_phone', 'car', 'bowl', 'sheep', 'potted_plant', 'microwave', 'couch', 'airplane', 
                  'sandwich', 'fork', 'traffic_light', 'scissors', 'carrot', 'book', 'vase', 'sink', 'orange', 'hot_dog',
                    'horse', 'donut', 'bed', 'wine_glass', 'bench', 'hair_drier', 'remote', 'surfboard', 'laptop', 'motorcycle',
                      'parking_meter', 'suitcase', 'keyboard', 'apple', 'cake', 'banana', 'person', 'toilet', 'fire_hydrant',
                        'toaster', 'umbrella', 'cat', 'cow', 'mouse', 'stop_sign', 'truck', 'spoon', 'handbag', 'bear', 
                        'broccoli', 'tv']
human_seen_name=['person_who_interact_with_donut', 'person_who_interact_with_tie', 'person_who_interact_with_potted_plant', 'person_who_interact_with_spoon', 'person_who_interact_with_sandwich', 'person_who_interact_with_traffic_light', 'person_who_interact_with_broccoli', 'person_who_interact_with_chair', 'person_who_interact_with_bus', 'person_who_interact_with_bench', 'person_who_interact_with_bird', 'person_who_interact_with_tv', 'person_who_interact_with_truck', 'person_who_interact_with_carrot', 'person_who_interact_with_oven', 'person_who_interact_with_sheep', 'person_who_interact_with_fire_hydrant', 'person_who_interact_with_laptop', 'person_who_interact_with_sink', 'person_who_interact_with_suitcase', 'person_who_interact_with_mouse', 'person_who_interact_with_stop_sign', 'person_who_interact_with_airplane', 'person_who_interact_with_train', 'person_who_interact_with_backpack', 'person_who_interact_with_motorcycle', 'person_who_interact_with_microwave', 'person_who_interact_with_couch', 'person_who_interact_with_cell_phone', 'person_who_interact_with_remote', 'person_who_interact_with_wine_glass', 'person_who_interact_with_cup', 'person_who_interact_with_knife', 'person_who_interact_with_keyboard', 'person_who_interact_with_person', 'person_who_interact_with_cat', 'person_who_interact_with_hot_dog', 'person_who_interact_with_cake', 'person_who_interact_with_kite', 'person_who_interact_with_bowl', 'person_who_interact_with_apple', 'person_who_interact_with_cow', 'person_who_interact_with_banana', 'person_who_interact_with_orange', 'person_who_interact_with_hair_drier', 'person_who_interact_with_handbag', 'person_who_interact_with_toilet', 'person_who_interact_with_horse', 'person_who_interact_with_bottle', 'person_who_interact_with_boat', 'person_who_interact_with_parking_meter', 'person_who_interact_with_toaster', 'person_who_interact_with_baseball_glove', 'person_who_interact_with_bear', 'person_who_interact_with_giraffe', 'person_who_interact_with_sports_ball', 'person_who_interact_with_vase', 'person_who_interact_with_car', 'person_who_interact_with_bed', 'person_who_interact_with_surfboard', 'person_who_interact_with_book', 'person_who_interact_with_teddy_bear', 'person_who_interact_with_snowboard', 'person_who_interact_with_fork', 'person_who_interact_with_bicycle', 'person_who_interact_with_scissors', 'person_who_interact_with_dining_table', 'person_who_interact_with_umbrella']


object_name=['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic_light', 'fire_hydrant', 'stop_sign', 'parking_meter',
             'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag',
             'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports_ball', 'kite', 'baseball_bat', 'baseball_glove', 'skateboard', 'surfboard',
             'tennis_racket', 'bottle', 'wine_glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli',
             'carrot', 'hot_dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted_plant', 'bed', 'dining_table', 'toilet', 'tv', 'laptop', 'mouse',
             'remote', 'keyboard', 'cell_phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy_bear',
             'hair_drier', 'toothbrush']
human_name=['person_who_interact_with_person', 'person_who_interact_with_bicycle', 'person_who_interact_with_car', 'person_who_interact_with_motorcycle', 'person_who_interact_with_airplane', 'person_who_interact_with_bus', 'person_who_interact_with_train', 'person_who_interact_with_truck',
            'person_who_interact_with_boat', 'person_who_interact_with_traffic_light', 'person_who_interact_with_fire_hydrant', 'person_who_interact_with_stop_sign', 'person_who_interact_with_parking_meter', 'person_who_interact_with_bench',
            'person_who_interact_with_bird', 'person_who_interact_with_cat', 'person_who_interact_with_dog', 'person_who_interact_with_horse', 'person_who_interact_with_sheep', 'person_who_interact_with_cow', 'person_who_interact_with_elephant', 'person_who_interact_with_bear',
            'person_who_interact_with_zebra', 'person_who_interact_with_giraffe', 'person_who_interact_with_backpack', 'person_who_interact_with_umbrella', 'person_who_interact_with_handbag', 'person_who_interact_with_tie', 'person_who_interact_with_suitcase', 'person_who_interact_with_frisbee',
              'person_who_interact_with_skis', 'person_who_interact_with_snowboard', 'person_who_interact_with_sports_ball', 'person_who_interact_with_kite', 'person_who_interact_with_baseball_bat', 'person_who_interact_with_baseball_glove', 'person_who_interact_with_skateboard', 'person_who_interact_with_surfboard', 'person_who_interact_with_tennis_racket', 'person_who_interact_with_bottle', 'person_who_interact_with_wine_glass', 'person_who_interact_with_cup', 'person_who_interact_with_fork', 'person_who_interact_with_knife', 'person_who_interact_with_spoon', 'person_who_interact_with_bowl', 'person_who_interact_with_banana', 'person_who_interact_with_apple', 'person_who_interact_with_sandwich', 'person_who_interact_with_orange', 'person_who_interact_with_broccoli', 'person_who_interact_with_carrot', 'person_who_interact_with_hot_dog', 'person_who_interact_with_pizza', 'person_who_interact_with_donut', 'person_who_interact_with_cake', 'person_who_interact_with_chair', 'person_who_interact_with_couch', 'person_who_interact_with_potted_plant', 'person_who_interact_with_bed', 'person_who_interact_with_dining_table', 'person_who_interact_with_toilet', 'person_who_interact_with_tv', 'person_who_interact_with_laptop', 'person_who_interact_with_mouse', 'person_who_interact_with_remote', 'person_who_interact_with_keyboard', 'person_who_interact_with_cell_phone', 'person_who_interact_with_microwave', 'person_who_interact_with_oven', 'person_who_interact_with_toaster', 'person_who_interact_with_sink', 'person_who_interact_with_refrigerator', 'person_who_interact_with_book', 'person_who_interact_with_clock', 'person_who_interact_with_vase', 'person_who_interact_with_scissors',
            'person_who_interact_with_teddy_bear', 'person_who_interact_with_hair_drier', 'person_who_interact_with_toothbrush']
human_for_verb_name=['action of the person is adjusting',
 'action of the person is assembling',
 'action of the person is blocking',
 'action of the person is blowing',
 'action of the person is boarding',
 'action of the person is breaking',
 'action of the person is brushing with',
 'action of the person is buying',
 'action of the person is carrying',
 'action of the person is catching',
 'action of the person is chasing',
 'action of the person is checking',
 'action of the person is cleaning',
 'action of the person is controling',
 'action of the person is cooking',
 'action of the person is cutting',
 'action of the person is cutting with',
 'action of the person is directing',
 'action of the person is draging',
 'action of the person is dribbling',
 'action of the person is drinking with',
 'action of the person is driving',
 'action of the person is drying',
 'action of the person is eating',
 'action of the person is eating at',
 'action of the person is exiting',
 'action of the person is feeding',
 'action of the person is filling',
 'action of the person is flipping',
 'action of the person is flushing',
 'action of the person is flying',
 'action of the person is greeting',
 'action of the person is grinding',
 'action of the person is grooming',
 'action of the person is herding',
 'action of the person is hiting',
 'action of the person is holding',
 'action of the person is hopping on',
 'action of the person is hosing',
 'action of the person is hugging',
 'action of the person is hunting',
 'action of the person is inspecting',
 'action of the person is installing',
 'action of the person is jumping',
 'action of the person is kicking',
 'action of the person is kissing',
 'action of the person is lassoing',
 'action of the person is launching',
 'action of the person is licking',
 'action of the person is lying on',
 'action of the person is lifting',
 'action of the person is lighting',
 'action of the person is loading',
 'action of the person is losing',
 'action of the person is making',
 'action of the person is milking',
 'action of the person is moving',
 'action of the person is no interaction with object',
 'action of the person is opening',
 'action of the person is operating',
 'action of the person is packing',
 'action of the person is painting',
 'action of the person is parking',
 'action of the person is paying',
 'action of the person is peeling',
 'action of the person is petting',
 'action of the person is picking',
 'action of the person is picking up',
 'action of the person is pointing',
 'action of the person is pouring',
 'action of the person is pulling',
 'action of the person is pushing',
 'action of the person is racing',
 'action of the person is reading',
 'action of the person is releasing',
 'action of the person is repairing',
 'action of the person is riding',
 'action of the person is rowing',
 'action of the person is running',
 'action of the person is sailing',
 'action of the person is scratching',
 'action of the person is serving',
 'action of the person is setting',
 'action of the person is shearing',
 'action of the person is signing',
 'action of the person is siping',
 'action of the person is sitting at',
 'action of the person is sitting on',
 'action of the person is sliding',
 'action of the person is smelling',
 'action of the person is spining',
 'action of the person is squeezing',
 'action of the person is stabbing',
 'action of the person is standing on',
 'action of the person is standing under',
 'action of the person is sticking',
 'action of the person is stirring',
 'action of the person is stopping at',
 'action of the person is straddling',
 'action of the person is swinging',
 'action of the person is tagging',
 'action of the person is talking on',
 'action of the person is teaching',
 'action of the person is texting on',
 'action of the person is throwing',
 'action of the person is tying',
 'action of the person is toasting',
 'action of the person is training',
 'action of the person is turning',
 'action of the person is typing on',
 'action of the person is walking',
 'action of the person is washing',
 'action of the person is watching',
 'action of the person is waving',
 'action of the person is wearing',
 'action of the person is wielding',
 'action of the person is zipping']
seen_classnames=['board airplane', 'direct airplane', 'exit airplane', 'fly airplane', 'inspect airplane', 'load airplane', 'ride airplane', 'sit_on airplane',
 'no_interaction airplane', 'carry bicycle', 'hold bicycle', 'inspect bicycle', 'jump bicycle', 'hop_on bicycle', 'park bicycle', 'push bicycle',
 'repair bicycle', 'ride bicycle', 'sit_on bicycle', 'straddle bicycle', 'walk bicycle', 'no_interaction bicycle', 'chase bird', 'feed bird', 'hold bird',
 'release bird', 'watch bird', 'no_interaction bird', 'board boat', 'drive boat', 'exit boat', 'inspect boat', 'jump boat', 'launch boat', 'repair boat', 'ride boat',
 'row boat', 'sail boat', 'sit_on boat', 'stand_on boat', 'tie boat', 'no_interaction boat', 'carry bottle', 'drink_with bottle', 'hold bottle', 'inspect bottle',
                 'open bottle', 'pour bottle', 'no_interaction bottle', 'board bus', 'drive bus', 'exit bus', 'inspect bus', 'load bus', 'ride bus', 'sit_on bus',
                 'wave bus', 'no_interaction bus', 'board car', 'drive car', 'hose car', 'inspect car', 'load car', 'park car', 'ride car', 'wash car',
                 'no_interaction car', 'hold cat', 'hug cat', 'pet cat', 'scratch cat', 'no_interaction cat', 'carry chair', 'hold chair', 'lie_on chair',
                 'sit_on chair', 'no_interaction chair', 'carry couch', 'lie_on couch', 'sit_on couch', 'no_interaction couch', 'feed cow', 'herd cow', 'hold cow',
                 'lasso cow', 'milk cow', 'pet cow', 'walk cow', 'no_interaction cow', 'eat_at dining_table', 'sit_at dining_table',
                 'no_interaction dining_table', 'carry dog', 'dry dog', 'feed dog', 'groom dog', 'hold dog', 'hose dog', 'hug dog', 'inspect dog', 'kiss dog',
                 'pet dog', 'run dog', 'scratch dog', 'straddle dog', 'train dog', 'walk dog', 'wash dog', 'no_interaction dog', 'feed horse', 'groom horse',
                 'hold horse', 'hug horse', 'jump horse', 'kiss horse', 'pet horse', 'race horse', 'ride horse', 'run horse', 'straddle horse', 'train horse',
                 'walk horse', 'wash horse', 'no_interaction horse', 'hold motorcycle', 'inspect motorcycle', 'jump motorcycle', 'park motorcycle', 'push motorcycle',
                 'race motorcycle', 'ride motorcycle', 'sit_on motorcycle', 'straddle motorcycle', 'turn motorcycle', 'walk motorcycle', 'no_interaction motorcycle',
                 'carry person', 'greet person', 'hold person', 'hug person', 'kiss person', 'stab person', 'tag person', 'teach person', 'no_interaction person',
                 'carry potted_plant', 'hold potted_plant', 'hose potted_plant', 'no_interaction potted_plant', 'carry sheep', 'feed sheep', 'herd sheep',
                 'hold sheep', 'hug sheep', 'pet sheep', 'shear sheep', 'walk sheep', 'no_interaction sheep', 'board train', 'drive train', 'ride train',
                 'sit_on train', 'no_interaction train', 'control tv', 'watch tv', 'no_interaction tv', 'cut apple', 'eat apple', 'hold apple', 'inspect apple',
                 'peel apple', 'pick apple', 'no_interaction apple', 'carry backpack', 'hold backpack', 'inspect backpack', 'open backpack', 'wear backpack',
                 'no_interaction backpack', 'buy banana', 'carry banana', 'eat banana', 'hold banana', 'inspect banana', 'peel banana', 'pick banana',
                 'no_interaction banana', 'break baseball_bat', 'carry baseball_bat', 'hold baseball_bat', 'sign baseball_bat', 'swing baseball_bat',
                 'wield baseball_bat', 'no_interaction baseball_bat', 'hold baseball_glove', 'wear baseball_glove', 'no_interaction baseball_glove',
                 'feed bear', 'hunt bear', 'watch bear', 'lie_on bed', 'sit_on bed', 'no_interaction bed', 'inspect bench', 'lie_on bench', 'sit_on bench',
                 'no_interaction bench', 'carry book', 'hold book', 'open book', 'read book', 'no_interaction book', 'hold bowl', 'stir bowl',
                 'no_interaction bowl', 'eat broccoli', 'hold broccoli', 'no_interaction broccoli', 'blow cake', 'carry cake', 'cut cake', 'eat cake',
                 'hold cake', 'light cake', 'make cake', 'pick_up cake', 'no_interaction cake', 'carry carrot', 'cut carrot', 'eat carrot', 'hold carrot',
                 'peel carrot', 'no_interaction carrot', 'carry cell_phone', 'hold cell_phone', 'read cell_phone', 'talk_on cell_phone', 'text_on cell_phone',
                 'check clock', 'hold clock', 'set clock', 'no_interaction clock', 'carry cup', 'drink_with cup', 'hold cup', 'inspect cup', 'pour cup',
                 'sip cup', 'smell cup', 'fill cup', 'no_interaction cup', 'buy donut', 'carry donut', 'eat donut', 'hold donut', 'make donut', 'pick_up donut',
                 'no_interaction donut', 'feed elephant', 'hold elephant', 'hug elephant', 'hop_on elephant', 'pet elephant', 'ride elephant', 'walk elephant',
                 'wash elephant', 'watch elephant', 'no_interaction elephant', 'inspect fire_hydrant', 'open fire_hydrant', 'paint fire_hydrant',
                 'no_interaction fire_hydrant', 'hold fork', 'lift fork', 'stick fork', 'no_interaction fork', 'block frisbee',
                 'catch frisbee', 'hold frisbee', 'spin frisbee', 'throw frisbee', 'no_interaction frisbee', 'feed giraffe', 'kiss giraffe', 'pet giraffe',
                 'watch giraffe', 'no_interaction giraffe', 'hold hair_drier', 'operate hair_drier', 'carry handbag', 'hold handbag', 'no_interaction handbag',
                 'carry hot_dog', 'cook hot_dog', 'eat hot_dog', 'hold hot_dog', 'make hot_dog', 'no_interaction hot_dog', 'carry keyboard', 'hold keyboard',
                 'type_on keyboard', 'no_interaction keyboard', 'assemble kite', 'carry kite', 'fly kite', 'hold kite', 'inspect kite', 'launch kite',
                 'pull kite', 'no_interaction kite', 'cut_with knife', 'hold knife', 'stick knife', 'wield knife', 'no_interaction knife', 'hold laptop',
                 'open laptop', 'read laptop', 'repair laptop', 'type_on laptop', 'no_interaction laptop', 'no_interaction microwave', 'control mouse', 'hold mouse',
                 'no_interaction mouse', 'hold orange', 'squeeze orange', 'no_interaction orange', 'hold oven', 'inspect oven', 'repair oven', 'operate oven',
                 'no_interaction oven', 'check parking_meter', 'pay parking_meter', 'no_interaction parking_meter', 'carry pizza', 'cook pizza', 'cut pizza',
                 'eat pizza', 'hold pizza', 'make pizza', 'pick_up pizza', 'slide pizza', 'no_interaction pizza', 'hold refrigerator', 'move refrigerator',
                 'open refrigerator', 'no_interaction refrigerator', 'hold remote', 'point remote', 'no_interaction remote', 'carry sandwich', 'eat sandwich',
                 'hold sandwich', 'make sandwich', 'no_interaction sandwich', 'cut_with scissors', 'hold scissors', 'open scissors', 'no_interaction scissors',
                 'repair sink', 'wash sink', 'no_interaction sink', 'carry skateboard', 'flip skateboard', 'grind skateboard', 'hold skateboard', 'jump skateboard',
                 'pick_up skateboard', 'ride skateboard', 'sit_on skateboard', 'stand_on skateboard', 'no_interaction skateboard', 'carry skis', 'hold skis',
                 'inspect skis', 'jump skis', 'pick_up skis', 'ride skis', 'stand_on skis', 'wear skis', 'no_interaction skis', 'carry snowboard', 'grind snowboard',
                 'hold snowboard', 'jump snowboard', 'ride snowboard', 'stand_on snowboard', 'wear snowboard', 'hold spoon', 'lick spoon', 'sip spoon',
                 'no_interaction spoon', 'block sports_ball', 'carry sports_ball', 'catch sports_ball', 'dribble sports_ball', 'hit sports_ball',
                 'hold sports_ball', 'inspect sports_ball', 'kick sports_ball', 'pick_up sports_ball', 'serve sports_ball', 'throw sports_ball',
                 'no_interaction sports_ball', 'hold stop_sign', 'stand_under stop_sign', 'no_interaction stop_sign', 'carry suitcase', 'drag suitcase',
                 'hold suitcase', 'load suitcase', 'open suitcase', 'pack suitcase', 'pick_up suitcase', 'zip suitcase', 'no_interaction suitcase', 'carry surfboard',
                 'hold surfboard', 'inspect surfboard', 'lie_on surfboard', 'ride surfboard', 'stand_on surfboard', 'sit_on surfboard',
                 'no_interaction surfboard', 'carry teddy_bear', 'hold teddy_bear', 'hug teddy_bear', 'no_interaction teddy_bear', 'carry tennis_racket',
                 'hold tennis_racket', 'swing tennis_racket', 'no_interaction tennis_racket', 'adjust tie', 'hold tie', 'inspect tie', 'pull tie',
                 'tie tie', 'wear tie', 'no_interaction tie', 'no_interaction toaster', 'clean toilet', 'flush toilet', 'repair toilet', 'sit_on toilet',
                 'no_interaction toilet', 'brush_with toothbrush', 'hold toothbrush', 'no_interaction toothbrush', 'install traffic_light',
                 'repair traffic_light', 'stand_under traffic_light', 'stop_at traffic_light', 'no_interaction traffic_light', 'direct truck', 'drive truck',
                 'inspect truck', 'load truck', 'repair truck', 'ride truck', 'sit_on truck', 'wash truck', 'no_interaction truck', 'carry umbrella',
                 'hold umbrella', 'lose umbrella', 'open umbrella', 'repair umbrella', 'stand_under umbrella', 'no_interaction umbrella', 'hold vase',
                 'make vase', 'no_interaction vase', 'fill wine_glass', 'hold wine_glass', 'sip wine_glass', 'toast wine_glass', 'no_interaction wine_glass', 'watch zebra']


if __name__=='__main__':
    print(all_classnames[66])
    print(object_name[46])






